<?php
namespace Model;

// hook model_RoleAuth_use.php

use App\Model;

class KvModel extends Model
{
    // hook model_RoleAuth_public_start.php
    public $table = 'kv';
	public $index = 'k';

    // hook model_RoleAuth_public_end.php

	public function read($k)
	{
		$data= parent::read(['k'=>$k], '*'); // TODO: Change the autogenerated stub
		return xn_json_decode($data['v']);
	}

	public function update($k, $v)
	{
		return parent::update(['k'=>$k], ['v'=>xn_json_encode($v)]); // TODO: Change the autogenerated stub
	}

	public function insert($k,$v)
	{
		return parent::insert(['k'=>$k,'v'=>xn_json_encode($v)]); // TODO: Change the autogenerated stub
	}

	public function select($array)
	{
		$data = parent::select(['k'=>$array]);
		$array=[];
		foreach ($data as $row){
			$array[$row['k']]=xn_json_decode($row['v']);
		}
		return $array;
	}

	// hook model_RoleAuth_start.php

    // hook model_RoleAuth_end.php
}
?>