<?php
namespace Model;

use Server\Libs\Model;//注意这里---不能用 App\Model 因为会死循环
// hook model_stat_use.php

class StatModel extends Model
{
    // hook model_stat_public_start.php
    public $table = 'zx_stat';
    // hook model_stat_public_end.php

    // hook model_stat_start.php
    public function ReadCount($t, $ww, $s)
    {

        ksort($ww);
        $ww = db_cond_to_sqladd($ww);
        $www = md5($ww);
        $num = $this->read(['t' => $t, 'w' => $www, 's' => $s, 'd' => 'count']);
        if (!empty($num['t'])) {
            return $num['v'];
        }
        return false;
    }

    public function ReadSum($t, $ww, $s)
    {
        ksort($ww);
        $ww = db_cond_to_sqladd($ww);
        $www = md5($ww);
        $num = $this->read(['t' => $t, 'w' => $www, 's' => $s, 'd' => 'sum']);
        if (!empty($num['t'])) {
            return $num['v'];
        }
        return false;
    }

    public function DelStat($table)
    {
        return $this->delete(['t' => $table]);
    }

    public function insert($data)
    {
        ksort($data['w']);
        $data['f'] = db_cond_to_sqladd($data['w']);
        $data['w'] = md5($data['f']);
        return parent::insert($data); // TODO: Change the autogenerated stub
    }

    // hook model_stat_end.php
}
?>