<?php

namespace App;
// hook model_use.php

Class Model extends \Server\Libs\Model
{
    // hook model_start.php


//    public function count($cond=[], $select = '*')
//    {
//        // hook model_count_start.php
//        $num = $this->Stat->ReadCount($this->table, $cond, $select);
//        if ($num === false) {
//            $num = parent::count($cond, $select); // TODO: Change the autogenerated stub
//            is_array($select) AND $select = implode(',', $select);
//            $this->Stat->insert(['t' => $this->table, 'w' => $cond, 's' => $select, 'd' => 'count', 'v' => $num]);
//        }
//        // hook model_count_end.php
//        return $num;
//    }
//
//    public function sum($sum, $cond=[])
//    {
//        // hook model_sum_start.php
//        $num = $this->Stat->ReadSum($this->table, $cond, $sum);
//        if ($num === false) {
//            $num = parent::sum($sum, $cond); // TODO: Change the autogenerated stub
//            $this->Stat->insert(['t' => $this->table, 'w' => $cond, 's' => $sum, 'd' => 'sum', 'v' => $num]);
//        }
//        // hook model_sum_end.php
//        return $num;
//    }
//
//    public function insert($data)
//    {
//        // hook model_insert_start.php
//        $this->Stat->DelStat($this->table);
//        return parent::insert($data); // TODO: Change the autogenerated stub
//
//    }
//
//    public function insertALL($data)
//    {
//        // hook model_insertall_start.php
//        $this->Stat->DelStat($this->table);
//        return parent::insertALL($data); // TODO: Change the autogenerated stub
//    }
//
//    public function insertGetId($data)
//    {
//        // hook model_insertgetid_start.php
//        $this->Stat->DelStat($this->table);
//        return parent::insertGetId($data); // TODO: Change the autogenerated stub
//    }
//
//    public function delete($cond)
//    {
//        // hook model_delete_start.php
//        $this->Stat->DelStat($this->table);
//        return parent::delete($cond); // TODO: Change the autogenerated stub
//    }
//
//    public function update($cond, $data)
//    {
//        // hook model_update_start.php
//        $this->Stat->DelStat($this->table);
//        // hook model_update_end.php
//        return parent::update($cond, $data); // TODO: Change the autogenerated stub
//    }

    // hook model_end.php
}
?>