<?php

namespace Payment\Interfaces;

class Heidong extends Order
{


    public function create($usrid, $money, $Type, $config)
    {
        $order = parent::create($usrid, $money, $Type, $config); // TODO: Change the autogenerated stub
        $this->AppUrl = $config['AppUrl'];
        $PayType = 'alipay_operation';
        //empty($config['AppSess']) && $config['AppSess']='alipay_sm';

        switch ($Type) {
//            case 10:
//                $PayType = 'wxpay_sm';
//                break;

            //pay_way=alipay_operation 转账
            //pay_way=alipay_static_qrcode 截图扫码
            case 20:
                $PayType ='alipay_static_qrcode';
                break;
//            case 30:
//                $PayType = 'quick';
//                break;
//            case 50:
//                $PayType = 'uppay';
//                break;
            default:
                $this->app->response('0001', [], '支付通道暂时关闭');

        }

        $formData = [
            'amount' => bcmul($order['Money'],0.01,2),
            'merchant_user_id' => $config['AppID'],
            'out_trade_no' => $order['OrderNo'],
            'return_url' => $this->ReturnUrl,
            'notify_url' => $this->NotifyUrl,
            "pay_mode"=>"alipay_h5",
            "sign_type"=>"MD5",
            'pay_way' => $PayType,
        ];

        $formData['sign'] = $this->makeSign($formData,$config['AppKey']);

        $data = $this->api('/gateway/merchant/order', json_encode($formData), ['Content-Type' => 'application/json']);

        if ($data['code'] == 200 && !empty($data['data']['pay_url'])) {
            $this->app->Order->update(['ID' => $order['ID']], ['PayOrderNo' => $data['data']['trade_order_no']]);
            $this->app->response('0000', [], '下单成功', $data['data']['pay_url'], 302);
        } else {
            $this->app->response('0001', [], '下单失败');
        }
    }

    public function Ratify($order, $data, $config){


        $formData = [
            'merchant_user_id' => $config['AppID'],
            'out_trade_no' => $order['OrderNo'],
            "sign_type"=>"MD5",
        ];

        $formData['sign'] = $this->makeSign($formData,$config['AppKey']);

        $data = $this->api('/gateway/merchant/query', json_encode($formData), ['Content-Type' => 'application/json']);

        if ($data['code'] == 200 && !empty($data['data']['trade_order_no'])) {
            if(($data['data']['order_status']=='SUCCESS'||$data['data']['order_status']=='success') &&!empty($data['data']['pay_amount'])){
                $order['RealMoney'] = $data['data']['pay_amount']*100;
                parent::Notify($order, $data, $config); // TODO: Change the autogenerated stub
                $this->app->response('0000', [], '订单支付成功');
            }
            $this->app->response('0001', [], '订单尚未支付');
        } else {
            $this->app->response('0001', [], '订单查询失败');
        }
    }

    public function Notify($order, $data, $config)
    {
        if ($order['Status'] == 1) {
            return 'success';
        }
        $sign = $data['sign'];
        unset($data['sign']);
        $_data = [
            'amount' => $data['amount'],
            'notify_time' => $data['notify_time'],
            'out_trade_no' => $data['out_trade_no'],
            'input_charset' => $data['input_charset'],
            'trade_no' => $data['trade_no'],
            'notify_id' => $data['notify_id'],
            'status' => $data['status'],
        ];

        if ($sign != $this->makeSign($_data, $config['AppKey'])) {
            return 'error';
        }
        if ($order['Status'] == 0) {
            if ($data['status'] == 'success'||$data['status'] == 'SUCCESS') {
                $order['RealMoney'] = $data['amount']*100;
                parent::Notify($order, $data, $config); // TODO: Change the autogenerated stub
                return 'success';
            } else {
                return 'error';
            }
        }

        return 'error';

    }

    public function makeSign($paramArr, $appSecret)
    {
        unset($paramArr['sign_type']);
        $sign = '';
        ksort($paramArr);
        foreach ($paramArr as $key => $val) {
            if ($key != '' && $val != '') {
                $sign .= '&' . $key . '=' . $val;
            }
        }
        $sign .= $appSecret;
        $sign = substr($sign, 1);
        $sign = md5($sign);
        return $sign;
    }

}