<?php

namespace Payment\Interfaces;

class Tongan extends Order
{


    public function create($usrid, $money, $Type, $config)
    {
        $order = parent::create($usrid, $money, $Type, $config); // TODO: Change the autogenerated stub
        $this->AppUrl = $config['AppUrl'];

        $formData = [
            'version' => '3.0',
            'method' =>'Gt.online.interface',
            'partner' =>  $config['AppID'],
            'banktype' => 'alipay_wxred',
            'paymoney' =>($order['Money']/100).'.00',
            "ordernumber"=>$order['OrderNo'],
            "callbackurl"=> $this->NotifyUrl,
            'hrefbackurl'=>$this->ReturnUrl,
            'notreturnpage'=>true
        ];

        $formData['sign'] =  $this->makeSign($order,$config);
        $data = $this->api('/api/v1/getway', $formData, ['Content-Type' => 'application/x-www-form-urlencoded']);
        if ($data['code'] == 0 ) {
            $this->app->Order->update(['ID' => $order['ID']], ['PayOrderNo' => $data['data']['tradeNo']]);
            $this->app->response('0000', [], '下单成功', $data['data']['payUrl'], 302);
        } else {
            $this->app->response('0001', [], '下单失败');
        }
    }

    public function Ratify($order, $data, $config){

    }

    public function Notify($order, $data, $config)
    {
        if ($order['Status'] == 1) {
            return 'SUCCESS';
        }
        $sign = $data['sign'];
        $signContent = strtolower(md5('partner='.$config['AppID'].'&ordernumber='.$order['OrderNo'].'&orderstatus='.$data['orderstatus'].'&paymoney='.$data['paymoney'].$config['AppKey']));
        /*
        if ($sign != $signContent) {
            xn_log($this->AppUrl. ' '.$signContent.'-'. $sign.'签名不正确', 'payapi_error');
            return 'no';
        }
        */

        if ($order['Status'] == 0) {
            if ($data['orderstatus'] == 1) {
                $order['RealMoney'] = $data['paymoney']*100;
                parent::Notify($order, $data, $config); // TODO: Change the autogenerated stub
                return 'SUCCESS';
            } else {
                return 'no';
            }
        }

        return 'no';

    }

    public function makeSign($order, $config)
    {
        $signContent =  strtolower(md5( 'version=3.0&method=Gt.online.interface&partner='.$config['AppID'].'&banktype=alipay_wxred&paymoney='.(($order['Money']/100).'.00&ordernumber='.$order['OrderNo'].'&callbackurl='.$this->NotifyUrl.$config['AppKey'])));
        return $signContent;
    }

}