<?php

namespace Payment\Interfaces;

class Yizhifu extends Order
{


    public function create($usrid, $money, $Type, $config)
    {
        $order = parent::create($usrid, $money, $Type, $config); // TODO: Change the autogenerated stub
        $this->AppUrl = $config['AppUrl'];

        //http://jingasd.cn/#/pages/index/index?uid=100&order_id=1842154812&order_type=alipay&order_price=100&order_name=测试支付&serverkey=a7a108c60be815eea3cd9005e444f890&redirect_url=http://www.baidu.com
        $formData = [
            'order_price' => bcmul($order['Money'],0.01,2),
            'order_id' => $order['OrderNo'],
            'order_type' =>'alipay',
            'order_name'=>'测试支付',
            'serverkey'=>$config['AppKey'],
            'redirect_url' => $this->NotifyUrl,
            'uid'=>$order['UsrID']
        ];

        return $this->app->response('0000', [], '下单成功', $this->AppUrl.'#/pages/index/index?'.http_build_query($formData), 302);

        /*
        $data = $this->api('/#/pages/index/index', $formData, ['Content-Type' => 'application/x-www-form-urlencoded']);
        if ($data['code'] == 0 ) {
            $this->app->Order->update(['ID' => $order['ID']], ['PayOrderNo' => $data['data']['tradeNo']]);
            $this->app->response('0000', [], '下单成功', $data['data']['payUrl'], 302);
        } else {
            $this->app->response('0001', [], '下单失败');
        }*/
    }

    public function Ratify($order, $data, $config){

    }

    public function Notify($order, $data, $config)
    {

        //支付成功服务器回调地址包含 http(s)://，当订单已支付会向这个url地址推送”一次“Get请求！包含三个参数order_id 、qr_price（实际支付金额） 、uid 和 sign加密方式为 md5(md5(order_id) + serverkey)
        if ($order['Status'] == 1) {
            return json_encode(['success'=>false,'msg'=>'订单已经支付过了']);
        }
        $sign = $data['sign'];
        xn_log('支付回调;'.json_encode($data),'order_notice');
        $signContent = md5(md5($order['OrderNo']) . $config['AppKey']);
        if(strtolower($sign) != strtolower($signContent))
        {
            return json_encode(['success'=>false,'msg'=>'验签失败']);
        }
        else{
            if ($order['Status'] == 0) {

                    $order['RealMoney'] = $data['qr_price']*100;
                    parent::Notify($order, $data, $config); // TODO: Change the autogenerated stub
                    return json_encode(['success'=>true,'msg'=>'回调成功']);

            }
        }

        return json_encode(['success'=>false,'msg'=>'服务器处理失败']);

    }

    public function makeSign($order, $config)
    {
        $signContent =  strtolower(md5( 'version=3.0&method=Gt.online.interface&partner='.$config['AppID'].'&banktype=alipay_wxred&paymoney='.(($order['Money']/100).'.00&ordernumber='.$order['OrderNo'].'&callbackurl='.$this->NotifyUrl.$config['AppKey'])));
        return $signContent;
    }

}